### ISSUE TITLE
GroovyRuntimeException-  Ambiguous method overloading

### ISSUE THREAD

**Issue by kr-pawan** [gigaSproule/swagger-gradle-plugin#110]
I'm using v1.0.4 and it fails with the following exception.

I've used only minimal annotations- 

**For a single `POST` API**
`@Operation(summary = "Create a new Resource",
          tags = {"myResource"},
          responses = {
                  @ApiResponse(
                          content = @Content(mediaType = "application/json",
                                  schema = @Schema(implementation = MyRequest.class))),
                  @ApiResponse(responseCode = "400", description = "Invalid request supplied"),
                  @ApiResponse(responseCode = "401", description = "User is not Authenticated") })`

The **swagger** task in gradle is as per `README` with only below output paramteres
       //templatePath = "${project.rootDir}/src/test/resources/strapdown.html.hbs"
        outputPath = "${project.rootDir}/swagger/generated/document.html"
        swaggerDirectory = "${project.rootDir}/swagger/generated/swagger-ui"
        //swaggerApiReader = 'com.wordnik.swagger.jaxrs.reader.DefaultJaxrsApiReader'
        //modelConverters = [ 'io.swagger.validator.BeanValidator' ]
        //attachSwaggerArtifact = true

**Exception is**
`groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method com.fasterxml.jackson.databind.ObjectMapper#readTree. Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
        [class com.fasterxml.jackson.core.JsonParser]
        [class [B]
        [class java.io.File]
        [class java.io.InputStream]
        [class java.io.Reader]
        [class java.lang.String]
        [class java.net.URL]
        at com.benjaminsproule.swagger.gradleplugin.model.SecurityDefinitionExtension.loadSecurityDefinitionsFromJsonFile(SecurityDefinitionExtension.groovy:88)
        at com.benjaminsproule.swagger.gradleplugin.model.SecurityDefinitionExtension.generateSecuritySchemeDefinitions(SecurityDefinitionExtension.groovy:65)
        at com.benjaminsproule.swagger.gradleplugin.model.SecurityDefinitionExtension.asSwaggerType(SecurityDefinitionExtension.groovy:56)
        at com.benjaminsproule.swagger.gradleplugin.model.SecurityDefinitionExtension.asSwaggerType(SecurityDefinitionExtension.groovy)
        at com.benjaminsproule.swagger.gradleplugin.model.Swagerable$asSwaggerType.call(Unknown Source)
        at com.benjaminsproule.swagger.gradleplugin.model.ApiSourceExtension.asSwaggerType(ApiSourceExtension.groovy:119)
        at com.benjaminsproule.swagger.gradleplugin.model.ApiSourceExtension.asSwaggerType(ApiSourceExtension.groovy)
        at com.benjaminsproule.swagger.gradleplugin.model.Swagerable$asSwaggerType.call(Unknown Source)`

**Comment by gigaSproule** [comment]
`Cannot resolve which method to invoke for [null]`. Looks like something is null, so it can't tell which method to call.

Either you're not providing a value somewhere, or the plugin be borked. Can you late your actual config?

**Comment by gigaSproule** [comment]
Are you able to provide any extra information?

**Comment by kr-pawan** [comment]
This is hard to diagnose. Though it's ok for me if you go ahead and close this issue for now.
