### ISSUE TITLE
java.lang.ClassNotFoundException with version 1.0.6 of plugin

### ISSUE THREAD

**Issue by dcp65** [gigaSproule/swagger-gradle-plugin#129]
I'm getting the following error in multiple Groovy JAX-RS projects after attempting an upgrade from version 1.0.4 to 1.0.6 of swagger-gradle-plugin:

```
Caused by: java.lang.ClassNotFoundException: 
        at com.benjaminsproule.swagger.gradleplugin.reader.AbstractReader.readImplicitParameters(AbstractReader.groovy:425)
        at com.benjaminsproule.swagger.gradleplugin.reader.JaxrsReader.parseMethod(JaxrsReader.groovy:396)
        at com.benjaminsproule.swagger.gradleplugin.reader.JaxrsReader$parseMethod$0.callCurrent(Unknown Source)
        at com.benjaminsproule.swagger.gradleplugin.reader.JaxrsReader.readClass(JaxrsReader.groovy:134)
        at com.benjaminsproule.swagger.gradleplugin.reader.JaxrsReader.readClass(JaxrsReader.groovy:72)
        at com.benjaminsproule.swagger.gradleplugin.reader.JaxrsReader.read(JaxrsReader.groovy:66)
        at com.benjaminsproule.swagger.gradleplugin.reader.ClassSwaggerReader$read.call(Unknown Source)
        at com.benjaminsproule.swagger.gradleplugin.GenerateSwaggerDocsTask.processApiSourceExtension(GenerateSwaggerDocsTask.groovy:86)
        at com.benjaminsproule.swagger.gradleplugin.GenerateSwaggerDocsTask.generateSwaggerDocuments(GenerateSwaggerDocsTask.groovy:66)
```

I make use of the `@ApiImplicitParam` Swagger annotation in all projects. Looks like it might relate to that.

**Comment by gigaSproule** [comment]
Must be the classpath update. Can you provide your relevant build.gradle config and maybe the relevant annotation?

**Comment by ishaigor** [comment]
It may be related to primitive types issue https://github.com/gigaSproule/swagger-gradle-plugin/pull/130

**Comment by Frozkata** [comment]
I can confirm that the issue is related to `@ApiImplicitParam`. The problem exists in 1.0.5 as well.

**Comment by mpodlodowski** [comment]
Any updates on this?

**Comment by gigaSproule** [comment]
Sorry, this has completely passed me by. I'll need to give myself a refresh.

**Comment by gigaSproule** [comment]
I have no idea why I changed it, but I've corrected it
