### ISSUE TITLE
Feature Request: put plugin dependencies on their own dependency configuration

### ISSUE THREAD

**Issue by montrivo** [gigaSproule/swagger-gradle-plugin#168]
I have a build with multiple plugins pulling in swagger dependencies on the builscript classpath dep configuration. They clash. It'd be nice if this plugin isolated its deps and tasks execution from the build classpath.

Here is an example of task failure I get when I run `./gradlew generateSwaggerDocumentation --stacktrace` in such  a project setup.

```
Caused by: java.util.ServiceConfigurationError: io.swagger.converter.ModelConverter: Provider io.swagger.scala.converter.SwaggerScalaModelConverter could not be instantiated
        at io.swagger.converter.ModelConverters.<clinit>(ModelConverters.java:129)
        at com.benjaminsproule.swagger.gradleplugin.misc.EnvironmentConfigurer.configureModelModifiers(EnvironmentConfigurer.groovy:102)
        at com.benjaminsproule.swagger.gradleplugin.misc.EnvironmentConfigurer$configureModelModifiers.call(Unknown Source)
        at com.benjaminsproule.swagger.gradleplugin.GenerateSwaggerDocsTask.generateSwaggerDocuments(GenerateSwaggerDocsTask.groovy:55)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
```

**Comment by gigaSproule** [comment]
This is a long time want of mine, but finding any time to do this is hard for me. If you feel inclined to correct this, I'd very much appreciate the PR.
