### ISSUE TITLE
Error in Springmvc project: AnnotatedElementUtils.findMergedAnnotation() 

### ISSUE THREAD

**Issue by wakingrufus** [gigaSproule/swagger-gradle-plugin#53]
When enabling version 1.0.2 of this plugin in our spring boot app, we get the following error:

```Caused by: org.gradle.api.GradleException: No signature of method: static org.springframework.core.annotation.AnnotatedElementUtils.findMergedAnnotation() is applicable for argument types: (java.lang.reflect.Method, java.lang.Class) values: [public abstract java.util.List our.org.OurClass.ourMethod(java.util.UUID,org.joda.time.DateTime,org.joda.time.DateTime), ...]
        at com.benjaminsproule.swagger.gradleplugin.GenerateSwaggerDocsTask.generateSwaggerDocuments(GenerateSwaggerDocsTask.groovy:59)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:228)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:621)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:604)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 60 more
Caused by: groovy.lang.MissingMethodException: No signature of method: static org.springframework.core.annotation.AnnotatedElementUtils.findMergedAnnotation() is applicable for argument types: (java.lang.reflect.Method, java.lang.Class) values: [public abstract java.util.List our.org.OurClass.ourMethod(java.util.UUID,org.joda.time.DateTime,org.joda.time.DateTime), ...]
        at com.benjaminsproule.swagger.gradleplugin.reader.SpringMvcApiReader.analyzeController(SpringMvcApiReader.groovy:378)
        at com.benjaminsproule.swagger.gradleplugin.reader.SpringMvcApiReader.generateResourceMap(SpringMvcApiReader.groovy:437)
        at com.benjaminsproule.swagger.gradleplugin.reader.SpringMvcApiReader.read(SpringMvcApiReader.groovy:52)
        at com.benjaminsproule.swagger.gradleplugin.reader.ClassSwaggerReader$read.call(Unknown Source)
        at com.benjaminsproule.swagger.gradleplugin.docgen.AbstractSwaggerLoader.loadDocuments(AbstractSwaggerLoader.groovy:31)
        at com.benjaminsproule.swagger.gradleplugin.docgen.AbstractSwaggerLoader$loadDocuments.call(Unknown Source)
        at com.benjaminsproule.swagger.gradleplugin.GenerateSwaggerDocsTask.processSwaggerPluginExtension(GenerateSwaggerDocsTask.groovy:73)
        at com.benjaminsproule.swagger.gradleplugin.GenerateSwaggerDocsTask.generateSwaggerDocuments(GenerateSwaggerDocsTask.groovy:52)
        ... 68 more
```

we have the `springmvc = true` option in the config.
we are using spring boot 1.4.7.RELEASE
and spring 4.3.12.RELEASE

I have tried gradle versions 2.14.1 and 4.5.1

**Comment by wakingrufus** [comment]
I suspect that this may be related to: https://jira.spring.io/browse/SPR-13708

**Comment by gigaSproule** [comment]
When I updated the `spring-boot-mvc` sample to use Spring boot 1.4.7.RELEASE, it worked perfectly fine. I then added `spring-test` version `4.3.12.RELEASE` (as seemed to be the issue in the Jira you linked), it worked fine still. Do you have an example of your build.gradle?

**Comment by cpoulsen-dezide** [comment]
FYI I have just tested with our spring mvc project (boot 2.0.0.RC1) and it reports no errors.

I can see that the swagger-gradle-plugin compiles against spring 5.x - Maybe something changed in the spring interface between v4 and 5 ?

**Comment by wakingrufus** [comment]
@cpoulsen-dezide The method looks the same between spring 4 and 5. I will take a closer look at our dependency tree. I was not previously looking at "spring-test" so I will look at that. Thanks.

**Comment by wakingrufus** [comment]
I got it working. Thanks.
