### ISSUE TITLE
modelSubstitute file is null

### ISSUE THREAD

**Issue by wakingrufus** [gigaSproule/swagger-gradle-plugin#56]
when I put a file called "models.txt" in my project's "src/main/resources" and set the modelSubstitute  configuration to "/models.txt", I get the following error:

```
Caused by: java.lang.NullPointerException: Cannot invoke method eachLine() on null object
        at com.benjaminsproule.swagger.gradleplugin.docgen.EnvironmentConfigurer.configureModelModifiers(EnvironmentConfigurer.groovy:87)
        at com.benjaminsproule.swagger.gradleplugin.docgen.EnvironmentConfigurer$configureModelModifiers.call(Unknown Source)
        at com.benjaminsproule.swagger.gradleplugin.docgen.LoaderFactory.configureGeneratorEnvironment(LoaderFactory.groovy:17)
        at com.benjaminsproule.swagger.gradleplugin.docgen.LoaderFactory.loader(LoaderFactory.groovy:8)
        at com.benjaminsproule.swagger.gradleplugin.docgen.LoaderFactory$loader.call(Unknown Source)
        at com.benjaminsproule.swagger.gradleplugin.GenerateSwaggerDocsTask.processSwaggerPluginExtension(GenerateSwaggerDocsTask.groovy:70)
        at com.benjaminsproule.swagger.gradleplugin.GenerateSwaggerDocsTask.generateSwaggerDocuments(GenerateSwaggerDocsTask.groovy:52)
        ... 83 more
```

Am I doing something wrong or is this a bug? There doesn't seem to be unit test coverage on this feature.

**Comment by gigaSproule** [comment]
I will try this out. I'm currently trying to improve the test coverage, but any help would be greatly appreciated (if you are able to).

**Comment by gigaSproule** [comment]
I managed to recreate it and even when I fixed it, there were other issues, so I will need to create some unit tests first (unless you start working on it)

**Comment by wakingrufus** [comment]
I will try to take some time to work on the tests this week, if my schedule allows

**Comment by wakingrufus** [comment]
I was able to create a very basic failing test by just adding a `modelSubstitute = "/models.txt"` line to the configuration in the spring and JaxRs tests. However, I can't figure out where I should put an actual "models.txt" file to make the test passable.

**Comment by BryanWisdom** [comment]
Thank you, this plugin is very useful!
I encountered the same problem. I was wondering if there is any reason why the model substitute cannot be a file on disk rather than a resource? There are already configurations for apiSource that require a file path. Making this a file path instead of a resource could reduce the complexity of needing to load extra dependencies to pick up an externally defined resource file.

**Comment by gigaSproule** [comment]
So in retrospect for this:
1. Make sure that this can read from disk and resources
2. Look into having a fall back that when a class is not available, just use the canonical name

**Comment by michaelruocco** [comment]
I believe that PR #65 should have fixed this?

**Comment by spyro2000** [comment]
Same problem here (nullpointer when placing the faile in resource folder)

**Comment by anwenyi** [comment]
I tried the same and get the same error.
mine txt looks like this:
com.type.StudendId : java.lang.String
