### ISSUE TITLE
Getting java.lang.ClassNotFoundException: javax.servlet.http.HttpServletRequest when generating swagger json

### ISSUE THREAD

**Issue by ssouris** [gigaSproule/swagger-gradle-plugin#59]
Spring Boot 1.5.2.RELEASE
Spring MVC

stacktrace
```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':ingress:generateSwaggerDocumentation'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.NoClassDefFoundError: javax/servlet/http/HttpServletRequest
        at com.benjaminsproule.swagger.gradleplugin.reader.SpringMvcApiReader.generateResourceMap(SpringMvcApiReader.groovy:444)
        at com.benjaminsproule.swagger.gradleplugin.reader.SpringMvcApiReader.read(SpringMvcApiReader.groovy:52)
        at com.benjaminsproule.swagger.gradleplugin.reader.ClassSwaggerReader$read.call(Unknown Source)
        at com.benjaminsproule.swagger.gradleplugin.docgen.AbstractSwaggerLoader.loadDocuments(AbstractSwaggerLoader.groovy:31)
        at com.benjaminsproule.swagger.gradleplugin.docgen.AbstractSwaggerLoader$loadDocuments.call(Unknown Source)
        at com.benjaminsproule.swagger.gradleplugin.GenerateSwaggerDocsTask.processSwaggerPluginExtension(GenerateSwaggerDocsTask.groovy:73)
        at com.benjaminsproule.swagger.gradleplugin.GenerateSwaggerDocsTask.generateSwaggerDocuments(GenerateSwaggerDocsTask.groovy:52)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:228)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:621)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:604)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 14 more
Caused by: java.lang.ClassNotFoundException: javax.servlet.http.HttpServletRequest
        ... 29 more
```

**Comment by ssouris** [comment]
Obviously I have `HttpServletRequest` as a parameter in one of my API calls, but it's on the classpath of the Spring Boot application. Can I do something about it? Fix the classpath while the gradle task is running?

**Comment by gigaSproule** [comment]
With the latest changes for 1.0.4, I can't replicate this issue. I'm guessing with all the classpath changes I've made, it's inadvertently fixed this.

**Comment by gigaSproule** [comment]
Going to close this and if the problem still persists after 1.0.4 has been released, we can re-open this issue.

**Comment by kauphylover** [comment]
I'm running into this issue with Spring Boot 2.1.1 and 1.0.6 version of this plugin. Here's a gradle scan for you to look at: https://gradle.com/s/3ufro57wxtcjq

It seems to be having issues with the ResponseEntityExceptionHandler being inside a RestController.
